# Generated by Django 4.2.5 on 2023-09-15 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_schema', models.JSONField()),
                ('example_context', models.JSONField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template_file', models.FileField(upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])])),
            ],
            options={
                'verbose_name': 'HTML Template',
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_schema', models.JSONField()),
                ('example_context', models.JSONField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template_file', models.FileField(upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'verbose_name': 'PDF Template',
            },
        ),
    ]
